### ISSUE TITLE
TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by vbauer** [depoio/node-telegram-bot#20]
I have a problem with app which was deployed on the OpenShift (node-telegram-bot version 0.0.16):

```
TypeError: Cannot call method 'split' of undefined
    at /var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/lib/Bot.js:90:44
    at Array.forEach (native)
    at Request._callback (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/lib/Bot.js:87:21)
    at Request.self.callback (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:197:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by fivepointseven** [comment]
My fault with command arguments recognition. It was fixed in my latest pull request (#17) but hasn't yet been merged. You can use fixed library from my repository until #17 is merged

**Comment by vbauer** [comment]
@fivepointseven Thank you for suggested solution! I hope it will be merged soon. :)

**Comment by shernshiou** [comment]
Thanks both. I will merge it now.
