### ISSUE TITLE
process._tickCallback

### ISSUE THREAD

**Issue by smhmayboudi** [depoio/node-telegram-bot#31]
/home/melobit/melobot-v2/node_modules/node-telegram-bot/node_modules/q/q.js:155
                throw e;
                      ^
TypeError: Cannot read property 'file_id' of undefined
    at /home/melobit/melobot-v2/commands/dl.js:36:56
    at /home/melobit/melobot-v2/node_modules/node-telegram-bot/node_modules/q/q.js:2031:17
    at runSingle (/home/melobit/melobot-v2/node_modules/node-telegram-bot/node_modules/q/q.js:137:13)
    at flush (/home/melobit/melobot-v2/node_modules/node-telegram-bot/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)

**Comment by shernshiou** [comment]
@smhmayboudi can you share your code snippet?
