### ISSUE TITLE
WHAT IS THIS PROBLEM - ECONNRESET?

### ISSUE THREAD

**Issue by smhmayboudi** [depoio/node-telegram-bot#33]
events.js:85                                                                                                                                                 │·······················
      throw er; // Unhandled 'error' event                                                                                                                   │·······················
            ^                                                                                                                                                │·······················
Error: read ECONNRESET                                                                                                                                       │·······················
    at exports._errnoException (util.js:746:11)                                                                                                              │·······················
    at Pipe.onread (net.js:559:26)                                                                                                                           │·······················

**Comment by Liryna** [comment]
https://stackoverflow.com/questions/17245881/node-js-econnreset

**Comment by shernshiou** [comment]
@smhmayboudi Can you attach some snippet so I can check?

@Liryna thanks.
