### ISSUE TITLE
Bot had no response to messages and crashed with TypeError

### ISSUE THREAD

**Issue by xavieryao** [depoio/node-telegram-bot#41]
```/Users/xavieryao/gengbot/node_modules/node-telegram-bot/lib/Bot.js:203
    } else if(res.statusCode === 401){
                 ^
TypeError: Cannot read property 'statusCode' of undefined
  at Request._callback (/Users/xavieryao/gengbot/node_modules/node-telegram-bot/lib/Bot.js:203:18)
  at self.callback (/Users/xavieryao/gengbot/node_modules/node-telegram-bot/node_modules/request/request.js:198:22)
  at Request.emit (events.js:107:17)
  at Request.onRequestError (/Users/xavieryao/gengbot/node_modules/node-telegram-bot/node_modules/request/request.js:877:8)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at net.js:459:14
  at process._tickCallback (node.js:355:11)
```

**Comment by xavieryao** [comment]
```[Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect'```

**Comment by xavieryao** [comment]
Turns out to be my internet failure.

**Comment by shernshiou** [comment]
Thanks for the report.. Will include more robust error message.
