### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by DrRamm** [depoio/node-telegram-bot#60]
Got this error when trying send photo in telegram -> bot 

/home/ubuntu/workspace/FacebookBot/node_modules/node-telegram-bot/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'destination' of undefined
    at callback (/home/ubuntu/workspace/FacebookBot/facebookbot.js:95:83)
    at /home/ubuntu/workspace/FacebookBot/node_modules/node-telegram-bot/node_modules/q/q.js:2031:17
    at runSingle (/home/ubuntu/workspace/FacebookBot/node_modules/node-telegram-bot/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/workspace/FacebookBot/node_modules/node-telegram-bot/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by shernshiou** [comment]
@DrRamm might need to see your snippets.
