### ISSUE TITLE
Error: Gateway error.

### ISSUE THREAD

**Issue by vbauer** [depoio/node-telegram-bot#81]
```
2016-08-24T11:49:37.598Z - info:  Error: Gateway error.
    at Request._callback (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/lib/Bot.js:273:28)
    at Request.self.callback (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/var/lib/openshift/55a967bc500446e3a9000060/app-root/runtime/repo/node_modules/node-telegram-bot/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by derhuerst** [comment]
That's Telegrams fault afaik.

**Comment by vbauer** [comment]
Probably, but is it possible to wrap this exception? In the current moment my bot suddenly breaks.

**Comment by derhuerst** [comment]
Why would you wrap that error? I think it is your responsibility you properly handle that error.

**Comment by vbauer** [comment]
I mean this error occurs in the part of node-telegram-bot library. Is it possible to handle somehow this exception in my code?

**Comment by derhuerst** [comment]
How do you receive the error?

**Comment by vbauer** [comment]
You can see full stacktrace in the description. That's all I have..

**Comment by derhuerst** [comment]
Did you get it in a callback or has it been thrown somewhere else?

**Comment by vbauer** [comment]
If I have got this information, I could catch this error and add some logging, but I do not know how to understand it using this stacktrace.

I see that error occurs somewhere in poll method inside pollingRequest: https://github.com/depoio/node-telegram-bot/blob/master/lib/Bot.js#L273

**Comment by derhuerst** [comment]
Do something like `bot.on('error', (err) => {/* handle error here */)`.

**Comment by vbauer** [comment]
Thank you for suggestion, I will try it as soon as possible!

**Comment by vbauer** [comment]
Hmm.. I've just checked source and I already have the following code (but bot was stopped anyway).

``` js
bot.on('error', function (error) {
    log(error);
});
```

Perhaps the problem was caused by OpenShift. Thank you for your time! I will reopen this ticket, if find something interesting.
