### ISSUE TITLE
Unhandled rejection Error: read ECONNRESET

### ISSUE THREAD

**Issue by xangel99** [depoio/node-telegram-bot#83]
Unhandled rejection Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TLSWrap.onread (net.js:557:26)

**Comment by theshaun** [comment]
This is not a new issue, referencing #79 

I've seen this happen every now and then when telegram derps up.

I don't believe this is a library issue unless you have more log data/steps to reproduce.
